// tslint:disable
/**
 * Kowabunga API documentation
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * The version of the OpenAPI document: 0.52.5
 * Contact: maintainers@kowabunga.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface ApiErrorUnprocessableEntity
 */
export interface ApiErrorUnprocessableEntity {
    /**
     * @type {number}
     * @memberof ApiErrorUnprocessableEntity
     */
    status: number;
    /**
     * @type {string}
     * @memberof ApiErrorUnprocessableEntity
     */
    error: string;
    /**
     * @type {string}
     * @memberof ApiErrorUnprocessableEntity
     */
    reason: string;
}
