// tslint:disable
/**
 * Kowabunga API documentation
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * The version of the OpenAPI document: 0.52.5
 * Contact: maintainers@kowabunga.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * A DNS record.
 * @export
 * @interface DnsRecord
 */
export interface DnsRecord {
    /**
     * The DNS record ID (auto-generated).
     * @type {string}
     * @memberof DnsRecord
     */
    id?: string;
    /**
     * The DNS record name.
     * @type {string}
     * @memberof DnsRecord
     */
    name: string;
    /**
     * The DNS record description.
     * @type {string}
     * @memberof DnsRecord
     */
    description?: string;
    /**
     * The DNS record associated domain (inherited from associated project).
     * @type {string}
     * @memberof DnsRecord
     */
    domain?: string;
    /**
     * A list of IPv4 addresses to be associated to the record.
     * @type {Array<string>}
     * @memberof DnsRecord
     */
    addresses: Array<string>;
}
