// tslint:disable
/**
 * Kowabunga API documentation
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * The version of the OpenAPI document: 0.52.5
 * Contact: maintainers@kowabunga.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * A virtual machine instance remote access characteristics.
 * @export
 * @interface InstanceRemoteAccess
 */
export interface InstanceRemoteAccess {
    /**
     * The virtual machine instance remote access URL.
     * @type {string}
     * @memberof InstanceRemoteAccess
     */
    url: string;
}
