// tslint:disable
/**
 * Kowabunga API
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * The version of the OpenAPI document: 0.53.1
 * Contact: maintainers@kowabunga.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * A virtual machine instance.
 * @export
 * @interface Instance
 */
export interface Instance {
    /**
     * The virtual machine instance ID (auto-generated).
     * @type {string}
     * @memberof Instance
     */
    id?: string;
    /**
     * The virtual machine instance name.
     * @type {string}
     * @memberof Instance
     */
    name: string;
    /**
     * The virtual machine instance description.
     * @type {string}
     * @memberof Instance
     */
    description?: string;
    /**
     * The virtual machine instance memory size (in bytes).
     * @type {number}
     * @memberof Instance
     */
    memory: number;
    /**
     * The virtual machine instance number of vCPUs.
     * @type {number}
     * @memberof Instance
     */
    vcpus: number;
    /**
     * a list of existing network adapters to be connected to the instance.
     * @type {Array<string>}
     * @memberof Instance
     */
    adapters?: Array<string>;
    /**
     * volumes list of existing storage volumes (i.e. disks) to be connected to the instance.
     * @type {Array<string>}
     * @memberof Instance
     */
    volumes?: Array<string>;
}
