// tslint:disable
/**
 * Kowabunga API documentation
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * The version of the OpenAPI document: 0.52.5
 * Contact: maintainers@kowabunga.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    Cost,
} from './';

/**
 * A Kaktus (Kowabunga Affordable KVM and Tight Underneath Storage) is an hyper-converged infrastructure (HCI) bare-metal node offering computing and distributed storage capabilites.
 * @export
 * @interface Kaktus
 */
export interface Kaktus {
    /**
     * The Kaktus computing node ID (auto-generated).
     * @type {string}
     * @memberof Kaktus
     */
    id?: string;
    /**
     * The Kaktus computing node name.
     * @type {string}
     * @memberof Kaktus
     */
    name: string;
    /**
     * The Kaktus computing node description.
     * @type {string}
     * @memberof Kaktus
     */
    description?: string;
    /**
     * @type {Cost}
     * @memberof Kaktus
     */
    cpu_cost?: Cost;
    /**
     * @type {Cost}
     * @memberof Kaktus
     */
    memory_cost?: Cost;
    /**
     * The Kaktus node CPU resource over-commit ratio. Overcommitting CPU resources for VMs means allocating more virtual CPUs (vCPUs) to the virtual machines (VMs) than the physical cores available on the node. This can help optimize the utilization of the node CPU and increase the density of VMs per node.
     * @type {number}
     * @memberof Kaktus
     */
    overcommit_cpu_ratio?: number;
    /**
     * The Kaktus node memory resource over-commit ratio. Memory overcommitment is a concept in computing that covers the assignment of more memory to virtual computing devices (or processes) than the physical machine they are hosted, or running on, actually has.
     * @type {number}
     * @memberof Kaktus
     */
    overcommit_memory_ratio?: number;
    /**
     * a list of existing remote agents managing the Kaktus node.
     * @type {Array<string>}
     * @memberof Kaktus
     */
    agents: Array<string>;
}
