// tslint:disable
/**
 * Kowabunga API documentation
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * The version of the OpenAPI document: 0.52.5
 * Contact: maintainers@kowabunga.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * A Kawaii VPC firewall forwarding rule.
 * @export
 * @interface KawaiiVpcForwardRule
 */
export interface KawaiiVpcForwardRule {
    /**
     * The transport layer protocol to forward public traffic to.
     * @type {string}
     * @memberof KawaiiVpcForwardRule
     */
    protocol?: KawaiiVpcForwardRuleProtocolEnum;
    /**
     * The port (or list of ports) to forward public traffic from. Ranges are accepted. Format is a-b,c-d (e.g. 443; 22,80,443; 80,443,3000-3005).
     * @type {string}
     * @memberof KawaiiVpcForwardRule
     */
    ports: string;
}

/**
 * @export
 * @enum {string}
 */
export enum KawaiiVpcForwardRuleProtocolEnum {
    Tcp = 'tcp',
    Udp = 'udp'
}

