// tslint:disable
/**
 * Kowabunga API documentation
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * The version of the OpenAPI document: 0.52.5
 * Contact: maintainers@kowabunga.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    KawaiiDNatRule,
    KawaiiFirewall,
    KawaiiIpSec,
    KawaiiNetIp,
    KawaiiVpcPeering,
} from './';

/**
 * A Kawaii (Kowabunga Adapative WAn Intelligent Interface) is a network gateway used for your Internet inbound and outbound traffic.
 * @export
 * @interface Kawaii
 */
export interface Kawaii {
    /**
     * The Kawaii ID (auto-generated).
     * @type {string}
     * @memberof Kawaii
     */
    id?: string;
    /**
     * The Kawaii name.
     * @type {string}
     * @memberof Kawaii
     */
    name?: string;
    /**
     * The Kawaii description.
     * @type {string}
     * @memberof Kawaii
     */
    description?: string;
    /**
     * @type {KawaiiNetIp}
     * @memberof Kawaii
     */
    netip?: KawaiiNetIp;
    /**
     * @type {KawaiiFirewall}
     * @memberof Kawaii
     */
    firewall?: KawaiiFirewall;
    /**
     * The Kawaii list of NAT forwarding entries. Kawaii will forward public Internet traffic from all public virtual IPs to requested private subnet IP addresses.
     * @type {Array<KawaiiDNatRule>}
     * @memberof Kawaii
     */
    dnat?: Array<KawaiiDNatRule>;
    /**
     * The Kawaii list of Kowabunga private VPC subnet peering entries.
     * @type {Array<KawaiiVpcPeering>}
     * @memberof Kawaii
     */
    vpc_peerings?: Array<KawaiiVpcPeering>;
    /**
     * The Kawaii list of Kowabunga IPsec connections.
     * @type {Array<KawaiiIpSec>}
     * @memberof Kawaii
     */
    ipsec_connections?: Array<KawaiiIpSec>;
}
