// tslint:disable
/**
 * Kowabunga API documentation
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * The version of the OpenAPI document: 0.52.5
 * Contact: maintainers@kowabunga.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    KawaiiVpcForwardRule,
    KawaiiVpcNetIpZone,
} from './';

/**
 * A Kawaii internal VPC subnet peering.
 * @export
 * @interface KawaiiVpcPeering
 */
export interface KawaiiVpcPeering {
    /**
     * Kowabunga Subnet ID to be peered with (subnet local IP addresses will be automatically assigned to Kawaii instances)..
     * @type {string}
     * @memberof KawaiiVpcPeering
     */
    subnet: string;
    /**
     * The default VPC traffic forwarding policy.
     * @type {string}
     * @memberof KawaiiVpcPeering
     */
    policy?: KawaiiVpcPeeringPolicyEnum;
    /**
     * The firewall list of forwarding ingress rules from VPC peered subnet. ICMP traffic is always accepted. The specified ruleset will be explicitly accepted if drop is the default policy (useless otherwise).
     * @type {Array<KawaiiVpcForwardRule>}
     * @memberof KawaiiVpcPeering
     */
    ingress?: Array<KawaiiVpcForwardRule>;
    /**
     * The firewall list of forwarding egress rules to VPC peered subnet. ICMP traffic is always accepted. The specified ruleset will be explicitly accepted if drop is the default policy (useless otherwise).
     * @type {Array<KawaiiVpcForwardRule>}
     * @memberof KawaiiVpcPeering
     */
    egress?: Array<KawaiiVpcForwardRule>;
    /**
     * The per-zone auto-assigned private IPs in peered subnet (read-only).
     * @type {Array<KawaiiVpcNetIpZone>}
     * @memberof KawaiiVpcPeering
     */
    netip?: Array<KawaiiVpcNetIpZone>;
}

/**
 * @export
 * @enum {string}
 */
export enum KawaiiVpcPeeringPolicyEnum {
    Accept = 'accept',
    Drop = 'drop'
}

