// tslint:disable
/**
 * Kowabunga API documentation
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * The version of the OpenAPI document: 0.52.5
 * Contact: maintainers@kowabunga.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * A global project resource quotas/usage (0 for unlimited).
 * @export
 * @interface ProjectResources
 */
export interface ProjectResources {
    /**
     * The maximum total number of vCPUs allowed to be consumed by sum of all instances.
     * @type {number}
     * @memberof ProjectResources
     */
    vcpus?: number;
    /**
     * The maximum total memory (in bytes) allowed to be consumed by sum of all instances.
     * @type {number}
     * @memberof ProjectResources
     */
    memory?: number;
    /**
     * The maximum total disk capacity allowed to be consumed by sum of all instances.
     * @type {number}
     * @memberof ProjectResources
     */
    storage?: number;
    /**
     * The maximum number of instances allowed to be spawned.
     * @type {number}
     * @memberof ProjectResources
     */
    instances?: number;
}
