// tslint:disable
/**
 * Kowabunga API documentation
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * The version of the OpenAPI document: 0.52.5
 * Contact: maintainers@kowabunga.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * A region/subnet map.
 * @export
 * @interface RegionSubnet
 */
export interface RegionSubnet {
    /**
     * The region key.
     * @type {string}
     * @memberof RegionSubnet
     */
    key?: string;
    /**
     * The subnet ID.
     * @type {string}
     * @memberof RegionSubnet
     */
    value?: string;
}
