// tslint:disable
/**
 * Kowabunga API documentation
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * The version of the OpenAPI document: 0.52.5
 * Contact: maintainers@kowabunga.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * A Kowabunga users team.
 * @export
 * @interface Team
 */
export interface Team {
    /**
     * The Kowabunga users team ID (auto-generated).
     * @type {string}
     * @memberof Team
     */
    id?: string;
    /**
     * The Kowabunga users team name.
     * @type {string}
     * @memberof Team
     */
    name: string;
    /**
     * The Kowabunga users team description.
     * @type {string}
     * @memberof Team
     */
    description?: string;
    /**
     * List of user IDs that are part of the team.
     * @type {Array<string>}
     * @memberof Team
     */
    users: Array<string>;
}
