// tslint:disable
/**
 * Kowabunga API documentation
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * The version of the OpenAPI document: 0.52.5
 * Contact: maintainers@kowabunga.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * A image template.
 * @export
 * @interface Template
 */
export interface Template {
    /**
     * The image template ID (auto-generated).
     * @type {string}
     * @memberof Template
     */
    id?: string;
    /**
     * The image template name.
     * @type {string}
     * @memberof Template
     */
    name: string;
    /**
     * The image template description.
     * @type {string}
     * @memberof Template
     */
    description?: string;
    /**
     * Type of operating system if OS kind (useful to determine cloud-init parameters for instance).
     * @type {string}
     * @memberof Template
     */
    os?: TemplateOsEnum;
    /**
     * HTTP(s) source URL of the KVM-ready OS image.
     * @type {string}
     * @memberof Template
     */
    source: string;
}

/**
 * @export
 * @enum {string}
 */
export enum TemplateOsEnum {
    Linux = 'linux',
    Windows = 'windows'
}

