/**
 * Kowabunga API documentation
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * The version of the OpenAPI document: 0.52.5
 * Contact: maintainers@kowabunga.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { autoinject } from 'aurelia-framework';
import { HttpClient } from 'aurelia-http-client';
import { Api } from './Api';
import { AuthStorage } from './AuthStorage';
import {
  Adapter,
} from './models';

/**
 * deleteAdapter - parameters interface
 */
export interface IDeleteAdapterParams {
  adapterId: string;
}

/**
 * listAdapters - parameters interface
 */
export interface IListAdaptersParams {
}

/**
 * readAdapter - parameters interface
 */
export interface IReadAdapterParams {
  adapterId: string;
}

/**
 * updateAdapter - parameters interface
 */
export interface IUpdateAdapterParams {
  adapterId: string;
  adapter: Adapter;
}

/**
 * AdapterApi - API class
 */
@autoinject()
export class AdapterApi extends Api {

  /**
   * Creates a new AdapterApi class.
   *
   * @param httpClient The Aurelia HTTP client to be injected.
   * @param authStorage A storage for authentication data.
   */
  constructor(httpClient: HttpClient, authStorage: AuthStorage) {
    super(httpClient, authStorage);
  }

  /**
   * Deletes an existing network adapter.
   * @param params.adapterId The ID of the network adapter.
   */
  async deleteAdapter(params: IDeleteAdapterParams): Promise<any> {
    // Verify required parameters are set
    this.ensureParamIsSet('deleteAdapter', params, 'adapterId');

    // Create URL to call
    const url = `${this.basePath}/adapter/{adapterId}`
      .replace(`{${'adapterId'}}`, encodeURIComponent(`${params['adapterId']}`));

    const response = await this.httpClient.createRequest(url)
      // Set HTTP method
      .asDelete()

      // Authentication 'ApiKeyAuth' required
      .withHeader('X-API-Key', this.authStorage.getApiKeyAuth())
      // Authentication 'BearerAuth' required
      // Send the request
      .send();

    if (response.statusCode < 200 || response.statusCode >= 300) {
      throw new Error(response.content);
    }

    // Extract the content
    return response.content;
  }

  /**
   * Returns the IDs of network adapter objects.
   */
  async listAdapters(): Promise<Array<string>> {
    // Verify required parameters are set

    // Create URL to call
    const url = `${this.basePath}/adapter`;

    const response = await this.httpClient.createRequest(url)
      // Set HTTP method
      .asGet()

      // Authentication 'ApiKeyAuth' required
      .withHeader('X-API-Key', this.authStorage.getApiKeyAuth())
      // Authentication 'BearerAuth' required
      // Send the request
      .send();

    if (response.statusCode < 200 || response.statusCode >= 300) {
      throw new Error(response.content);
    }

    // Extract the content
    return response.content;
  }

  /**
   * Returns a network adapter.
   * @param params.adapterId The ID of the network adapter.
   */
  async readAdapter(params: IReadAdapterParams): Promise<Adapter> {
    // Verify required parameters are set
    this.ensureParamIsSet('readAdapter', params, 'adapterId');

    // Create URL to call
    const url = `${this.basePath}/adapter/{adapterId}`
      .replace(`{${'adapterId'}}`, encodeURIComponent(`${params['adapterId']}`));

    const response = await this.httpClient.createRequest(url)
      // Set HTTP method
      .asGet()

      // Authentication 'ApiKeyAuth' required
      .withHeader('X-API-Key', this.authStorage.getApiKeyAuth())
      // Authentication 'BearerAuth' required
      // Send the request
      .send();

    if (response.statusCode < 200 || response.statusCode >= 300) {
      throw new Error(response.content);
    }

    // Extract the content
    return response.content;
  }

  /**
   * Updates a network adapter configuration.
   * @param params.adapterId The ID of the network adapter.
   * @param params.adapter Adapter payload.
   */
  async updateAdapter(params: IUpdateAdapterParams): Promise<Adapter> {
    // Verify required parameters are set
    this.ensureParamIsSet('updateAdapter', params, 'adapterId');
    this.ensureParamIsSet('updateAdapter', params, 'adapter');

    // Create URL to call
    const url = `${this.basePath}/adapter/{adapterId}`
      .replace(`{${'adapterId'}}`, encodeURIComponent(`${params['adapterId']}`));

    const response = await this.httpClient.createRequest(url)
      // Set HTTP method
      .asPut()
      // Encode body parameter
      .withHeader('content-type', 'application/json')
      .withContent(JSON.stringify(params['adapter'] || {}))

      // Authentication 'ApiKeyAuth' required
      .withHeader('X-API-Key', this.authStorage.getApiKeyAuth())
      // Authentication 'BearerAuth' required
      // Send the request
      .send();

    if (response.statusCode < 200 || response.statusCode >= 300) {
      throw new Error(response.content);
    }

    // Extract the content
    return response.content;
  }

}

