/**
 * Kowabunga API documentation
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * The version of the OpenAPI document: 0.52.5
 * Contact: maintainers@kowabunga.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { autoinject } from 'aurelia-framework';
import { HttpClient } from 'aurelia-http-client';
import { Api } from './Api';
import { AuthStorage } from './AuthStorage';
import {
  Kylo,
} from './models';

/**
 * deleteKylo - parameters interface
 */
export interface IDeleteKyloParams {
  kyloId: string;
}

/**
 * listKylos - parameters interface
 */
export interface IListKylosParams {
}

/**
 * readKylo - parameters interface
 */
export interface IReadKyloParams {
  kyloId: string;
}

/**
 * updateKylo - parameters interface
 */
export interface IUpdateKyloParams {
  kyloId: string;
  kylo: Kylo;
}

/**
 * KyloApi - API class
 */
@autoinject()
export class KyloApi extends Api {

  /**
   * Creates a new KyloApi class.
   *
   * @param httpClient The Aurelia HTTP client to be injected.
   * @param authStorage A storage for authentication data.
   */
  constructor(httpClient: HttpClient, authStorage: AuthStorage) {
    super(httpClient, authStorage);
  }

  /**
   * Deletes an existing Kylo.
   * @param params.kyloId The ID of the Kylo.
   */
  async deleteKylo(params: IDeleteKyloParams): Promise<any> {
    // Verify required parameters are set
    this.ensureParamIsSet('deleteKylo', params, 'kyloId');

    // Create URL to call
    const url = `${this.basePath}/kylo/{kyloId}`
      .replace(`{${'kyloId'}}`, encodeURIComponent(`${params['kyloId']}`));

    const response = await this.httpClient.createRequest(url)
      // Set HTTP method
      .asDelete()

      // Authentication 'ApiKeyAuth' required
      .withHeader('X-API-Key', this.authStorage.getApiKeyAuth())
      // Authentication 'BearerAuth' required
      // Send the request
      .send();

    if (response.statusCode < 200 || response.statusCode >= 300) {
      throw new Error(response.content);
    }

    // Extract the content
    return response.content;
  }

  /**
   * Returns the IDs of Kylo objects.
   */
  async listKylos(): Promise<Array<string>> {
    // Verify required parameters are set

    // Create URL to call
    const url = `${this.basePath}/kylo`;

    const response = await this.httpClient.createRequest(url)
      // Set HTTP method
      .asGet()

      // Authentication 'ApiKeyAuth' required
      .withHeader('X-API-Key', this.authStorage.getApiKeyAuth())
      // Authentication 'BearerAuth' required
      // Send the request
      .send();

    if (response.statusCode < 200 || response.statusCode >= 300) {
      throw new Error(response.content);
    }

    // Extract the content
    return response.content;
  }

  /**
   * Returns a Kylo.
   * @param params.kyloId The ID of the Kylo.
   */
  async readKylo(params: IReadKyloParams): Promise<Kylo> {
    // Verify required parameters are set
    this.ensureParamIsSet('readKylo', params, 'kyloId');

    // Create URL to call
    const url = `${this.basePath}/kylo/{kyloId}`
      .replace(`{${'kyloId'}}`, encodeURIComponent(`${params['kyloId']}`));

    const response = await this.httpClient.createRequest(url)
      // Set HTTP method
      .asGet()

      // Authentication 'ApiKeyAuth' required
      .withHeader('X-API-Key', this.authStorage.getApiKeyAuth())
      // Authentication 'BearerAuth' required
      // Send the request
      .send();

    if (response.statusCode < 200 || response.statusCode >= 300) {
      throw new Error(response.content);
    }

    // Extract the content
    return response.content;
  }

  /**
   * Updates a Kylo configuration.
   * @param params.kyloId The ID of the Kylo.
   * @param params.kylo Kylo payload.
   */
  async updateKylo(params: IUpdateKyloParams): Promise<Kylo> {
    // Verify required parameters are set
    this.ensureParamIsSet('updateKylo', params, 'kyloId');
    this.ensureParamIsSet('updateKylo', params, 'kylo');

    // Create URL to call
    const url = `${this.basePath}/kylo/{kyloId}`
      .replace(`{${'kyloId'}}`, encodeURIComponent(`${params['kyloId']}`));

    const response = await this.httpClient.createRequest(url)
      // Set HTTP method
      .asPut()
      // Encode body parameter
      .withHeader('content-type', 'application/json')
      .withContent(JSON.stringify(params['kylo'] || {}))

      // Authentication 'ApiKeyAuth' required
      .withHeader('X-API-Key', this.authStorage.getApiKeyAuth())
      // Authentication 'BearerAuth' required
      // Send the request
      .send();

    if (response.statusCode < 200 || response.statusCode >= 300) {
      throw new Error(response.content);
    }

    // Extract the content
    return response.content;
  }

}

