/**
 * Kowabunga API documentation
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * The version of the OpenAPI document: 0.52.5
 * Contact: maintainers@kowabunga.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { autoinject } from 'aurelia-framework';
import { HttpClient } from 'aurelia-http-client';
import { Api } from './Api';
import { AuthStorage } from './AuthStorage';
import {
  DnsRecord,
} from './models';

/**
 * deleteDnsRecord - parameters interface
 */
export interface IDeleteDnsRecordParams {
  recordId: string;
}

/**
 * readDnsRecord - parameters interface
 */
export interface IReadDnsRecordParams {
  recordId: string;
}

/**
 * updateDnsRecord - parameters interface
 */
export interface IUpdateDnsRecordParams {
  recordId: string;
  dnsRecord: DnsRecord;
}

/**
 * RecordApi - API class
 */
@autoinject()
export class RecordApi extends Api {

  /**
   * Creates a new RecordApi class.
   *
   * @param httpClient The Aurelia HTTP client to be injected.
   * @param authStorage A storage for authentication data.
   */
  constructor(httpClient: HttpClient, authStorage: AuthStorage) {
    super(httpClient, authStorage);
  }

  /**
   * Deletes an existing DNS record.
   * @param params.recordId The ID of the DNS record.
   */
  async deleteDnsRecord(params: IDeleteDnsRecordParams): Promise<any> {
    // Verify required parameters are set
    this.ensureParamIsSet('deleteDnsRecord', params, 'recordId');

    // Create URL to call
    const url = `${this.basePath}/record/{recordId}`
      .replace(`{${'recordId'}}`, encodeURIComponent(`${params['recordId']}`));

    const response = await this.httpClient.createRequest(url)
      // Set HTTP method
      .asDelete()

      // Authentication 'ApiKeyAuth' required
      .withHeader('X-API-Key', this.authStorage.getApiKeyAuth())
      // Authentication 'BearerAuth' required
      // Send the request
      .send();

    if (response.statusCode < 200 || response.statusCode >= 300) {
      throw new Error(response.content);
    }

    // Extract the content
    return response.content;
  }

  /**
   * Returns a DNS record.
   * @param params.recordId The ID of the DNS record.
   */
  async readDnsRecord(params: IReadDnsRecordParams): Promise<DnsRecord> {
    // Verify required parameters are set
    this.ensureParamIsSet('readDnsRecord', params, 'recordId');

    // Create URL to call
    const url = `${this.basePath}/record/{recordId}`
      .replace(`{${'recordId'}}`, encodeURIComponent(`${params['recordId']}`));

    const response = await this.httpClient.createRequest(url)
      // Set HTTP method
      .asGet()

      // Authentication 'ApiKeyAuth' required
      .withHeader('X-API-Key', this.authStorage.getApiKeyAuth())
      // Authentication 'BearerAuth' required
      // Send the request
      .send();

    if (response.statusCode < 200 || response.statusCode >= 300) {
      throw new Error(response.content);
    }

    // Extract the content
    return response.content;
  }

  /**
   * Updates a DNS record configuration.
   * @param params.recordId The ID of the DNS record.
   * @param params.dnsRecord DnsRecord payload.
   */
  async updateDnsRecord(params: IUpdateDnsRecordParams): Promise<DnsRecord> {
    // Verify required parameters are set
    this.ensureParamIsSet('updateDnsRecord', params, 'recordId');
    this.ensureParamIsSet('updateDnsRecord', params, 'dnsRecord');

    // Create URL to call
    const url = `${this.basePath}/record/{recordId}`
      .replace(`{${'recordId'}}`, encodeURIComponent(`${params['recordId']}`));

    const response = await this.httpClient.createRequest(url)
      // Set HTTP method
      .asPut()
      // Encode body parameter
      .withHeader('content-type', 'application/json')
      .withContent(JSON.stringify(params['dnsRecord'] || {}))

      // Authentication 'ApiKeyAuth' required
      .withHeader('X-API-Key', this.authStorage.getApiKeyAuth())
      // Authentication 'BearerAuth' required
      // Send the request
      .send();

    if (response.statusCode < 200 || response.statusCode >= 300) {
      throw new Error(response.content);
    }

    // Extract the content
    return response.content;
  }

}

