/**
 * Kowabunga API documentation
 *
 * Contact: maintainers@kowabunga.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A Kowabunga remote agent.
 */
export interface Agent { 
    /**
     * The Kowabunga remote agent ID (auto-generated).
     */
    id?: string;
    /**
     * The Kowabunga remote agent name.
     */
    name: string;
    /**
     * The Kowabunga remote agent description.
     */
    description?: string;
    /**
     * The Kowabunga agent type.
     */
    type: Agent.TypeEnum;
}
export namespace Agent {
    export type TypeEnum = 'Kiwi' | 'Kaktus';
    export const TypeEnum = {
        Kiwi: 'Kiwi' as TypeEnum,
        Kaktus: 'Kaktus' as TypeEnum
    };
}


