/**
 * Kowabunga API documentation
 *
 * Contact: maintainers@kowabunga.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A resource cost.
 */
export interface Cost { 
    /**
     * The unit price information.
     */
    price: number;
    /**
     * The associated currency.
     */
    currency: string;
}

