/**
 * Kowabunga API documentation
 *
 * Contact: maintainers@kowabunga.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A DNS record.
 */
export interface DnsRecord { 
    /**
     * The DNS record ID (auto-generated).
     */
    id?: string;
    /**
     * The DNS record name.
     */
    name: string;
    /**
     * The DNS record description.
     */
    description?: string;
    /**
     * The DNS record associated domain (inherited from associated project).
     */
    domain?: string;
    /**
     * A list of IPv4 addresses to be associated to the record.
     */
    addresses: Array<string>;
}

