/**
 * Kowabunga API documentation
 *
 * Contact: maintainers@kowabunga.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A virtual machine instance.
 */
export interface Instance { 
    /**
     * The virtual machine instance ID (auto-generated).
     */
    id?: string;
    /**
     * The virtual machine instance name.
     */
    name: string;
    /**
     * The virtual machine instance description.
     */
    description?: string;
    /**
     * The virtual machine instance memory size (in bytes).
     */
    memory: number;
    /**
     * The virtual machine instance number of vCPUs.
     */
    vcpus: number;
    /**
     * a list of existing network adapters to be connected to the instance.
     */
    adapters?: Array<string>;
    /**
     * volumes list of existing storage volumes (i.e. disks) to be connected to the instance.
     */
    volumes?: Array<string>;
}

