/**
 * Kowabunga API documentation
 *
 * Contact: maintainers@kowabunga.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { KaktusCPU } from './kaktusCPU';


/**
 * A Kaktus computing node capability.
 */
export interface KaktusCaps { 
    cpu: KaktusCPU;
    /**
     * The Kaktus computing node memory size (bytes).
     */
    memory: number;
}

