/**
 * Kowabunga API documentation
 *
 * Contact: maintainers@kowabunga.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { KawaiiNetIpZone } from './kawaiiNetIpZone';


/**
 * A Kawaii Network IP settings.
 */
export interface KawaiiNetIp { 
    /**
     * The Kawaii global public gateways virtual IP addresses (read-only).
     */
    'public': Array<string>;
    /**
     * The Kawaii global private gateways virtual IP addresses (read-only).
     */
    'private': Array<string>;
    /**
     * The Kawaii per-zone list of Kowabunga virtual IP addresses.
     */
    zones: Array<KawaiiNetIpZone>;
}

