/**
 * Kowabunga API documentation
 *
 * Contact: maintainers@kowabunga.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A Kawaii Network IP zone settings.
 */
export interface KawaiiNetIpZone { 
    /**
     * The Kawaii zone name (read-only).
     */
    zone: string;
    /**
     * The Kawaii zone gateway public virtual IP (read-only).
     */
    'public': string;
    /**
     * The Kawaii zone gateway private virtual IP (read-only).
     */
    'private': string;
}

