/**
 * Kowabunga API documentation
 *
 * Contact: maintainers@kowabunga.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { KawaiiFirewallIngressRule } from './kawaiiFirewallIngressRule';
import { KawaiiFirewallEgressRule } from './kawaiiFirewallEgressRule';


/**
 * A Kawaii public firewall settings.
 */
export interface KawaiiFirewall { 
    /**
     * The Kawaii public firewall list of ingress rules. Kawaii default policy is to drop all incoming traffic, including ICMP. Specified ruleset will be explicitly accepted.
     */
    ingress?: Array<KawaiiFirewallIngressRule>;
    /**
     * The default public traffic egress policy.
     */
    egress_policy?: KawaiiFirewall.EgressPolicyEnum;
    /**
     * The Kawaii public firewall list of egress rules. Kawaii default policy is to accept all outgoing traffic, including ICMP. Specified ruleset will be explicitly dropped if egress_policy is set to accept, and explicitly accepted if egress policy is set to drop..
     */
    egress?: Array<KawaiiFirewallEgressRule>;
}
export namespace KawaiiFirewall {
    export type EgressPolicyEnum = 'accept' | 'drop';
    export const EgressPolicyEnum = {
        Accept: 'accept' as EgressPolicyEnum,
        Drop: 'drop' as EgressPolicyEnum
    };
}


