/**
 * Kowabunga API documentation
 *
 * Contact: maintainers@kowabunga.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A Kawaii VPC firewall forwarding rule.
 */
export interface KawaiiVpcForwardRule { 
    /**
     * The transport layer protocol to forward public traffic to.
     */
    protocol?: KawaiiVpcForwardRule.ProtocolEnum;
    /**
     * The port (or list of ports) to forward public traffic from. Ranges are accepted. Format is a-b,c-d (e.g. 443; 22,80,443; 80,443,3000-3005).
     */
    ports: string;
}
export namespace KawaiiVpcForwardRule {
    export type ProtocolEnum = 'tcp' | 'udp';
    export const ProtocolEnum = {
        Tcp: 'tcp' as ProtocolEnum,
        Udp: 'udp' as ProtocolEnum
    };
}


