/**
 * Kowabunga API documentation
 *
 * Contact: maintainers@kowabunga.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A Kawaii VPC Network IP zone settings.
 */
export interface KawaiiVpcNetIpZone { 
    /**
     * The Kawaii zone name (read-only).
     */
    zone: string;
    /**
     * The Kawaii zone gateway private IP address in VPC peered subnet  (read-only).
     */
    'private': string;
}

