/**
 * Kowabunga API documentation
 *
 * Contact: maintainers@kowabunga.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A Kompute is a wrapper object for bare virtual machines. It consists of an instance, one to several attached volumes and 2 network adapters (a private one, a public one). This is the prefered way for creating virtual machines. IP addresses will be automatically assigned.
 */
export interface Kompute { 
    /**
     * The Kompute ID (auto-generated).
     */
    id?: string;
    /**
     * The Kompute name.
     */
    name: string;
    /**
     * The Kompute description.
     */
    description?: string;
    /**
     * The Kompute memory size (in bytes).
     */
    memory: number;
    /**
     * The Kompute number of vCPUs.
     */
    vcpus: number;
    /**
     * The Kompute OS disk size (in bytes).
     */
    disk: number;
    /**
     * The Kompute extra data disk size (in bytes). If unspecified, no extra data disk will be assigned.
     */
    data_disk?: number;
    /**
     * The Kompute assigned private IPv4 address (read-only).
     */
    ip?: string;
}

