/**
 * Kowabunga API documentation
 *
 * Contact: maintainers@kowabunga.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { KonveyBackends } from './konveyBackends';


/**
 * A Konvey Endpoint Service settings.
 */
export interface KonveyEndpoint { 
    /**
     * The Konvey (Kowabunga Network Load-Balancer) endpoint name.
     */
    name: string;
    /**
     * The port to be exposed.
     */
    port: number;
    /**
     * The transport layer protocol to be exposed.
     */
    protocol: KonveyEndpoint.ProtocolEnum;
    backends: KonveyBackends;
}
export namespace KonveyEndpoint {
    export type ProtocolEnum = 'tcp' | 'udp';
    export const ProtocolEnum = {
        Tcp: 'tcp' as ProtocolEnum,
        Udp: 'udp' as ProtocolEnum
    };
}


