/**
 * Kowabunga API documentation
 *
 * Contact: maintainers@kowabunga.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A Kylo provides an elastic NFS-like remote storage volume.
 */
export interface Kylo { 
    /**
     * The Kylo ID (auto-generated).
     */
    id?: string;
    /**
     * The Kylo name.
     */
    name: string;
    /**
     * The Kylo description.
     */
    description?: string;
    /**
     * The Kylo volume access type.
     */
    access?: Kylo.AccessEnum;
    /**
     * The Kylo NFS protocol versions to be supported.
     */
    protocols?: Array<Kylo.ProtocolsEnum>;
    /**
     * The Kylo endpoint FQDN (read-only).
     */
    endpoint?: string;
    /**
     * The Kylo volume bytes used (read-only).
     */
    size?: number;
}
export namespace Kylo {
    export type AccessEnum = 'RO' | 'RW';
    export const AccessEnum = {
        Ro: 'RO' as AccessEnum,
        Rw: 'RW' as AccessEnum
    };
    export type ProtocolsEnum = 3 | 4;
    export const ProtocolsEnum = {
        NUMBER_3: 3 as ProtocolsEnum,
        NUMBER_4: 4 as ProtocolsEnum
    };
}


