/**
 * Kowabunga API documentation
 *
 * Contact: maintainers@kowabunga.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A region.
 */
export interface Region { 
    /**
     * The region ID (auto-generated).
     */
    id?: string;
    /**
     * The region name.
     */
    name: string;
    /**
     * The region description.
     */
    description?: string;
}

