/**
 * Kowabunga API documentation
 *
 * Contact: maintainers@kowabunga.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A region/subnet map.
 */
export interface RegionSubnet { 
    /**
     * The region key.
     */
    key?: string;
    /**
     * The subnet ID.
     */
    value?: string;
}

