/**
 * Kowabunga API documentation
 *
 * Contact: maintainers@kowabunga.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A NFS storage.
 */
export interface StorageNFS { 
    /**
     * The NFS storage ID (auto-generated).
     */
    id?: string;
    /**
     * The NFS storage name.
     */
    name: string;
    /**
     * The NFS storage description.
     */
    description?: string;
    /**
     * The associated NFS endpoint FQDN.
     */
    endpoint: string;
    /**
     * The underlying associated Ceph volume name.
     */
    fs?: string;
    /**
     * List of NFS Ganesha API server IP addresses.
     */
    backends?: Array<string>;
    /**
     * NFS Ganesha API server port (default 54934).
     */
    port?: number;
}

