/**
 * Kowabunga API documentation
 *
 * Contact: maintainers@kowabunga.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IpRange } from './ipRange';


/**
 * A network subnet.
 */
export interface Subnet { 
    /**
     * The network subnet ID (auto-generated).
     */
    id?: string;
    /**
     * The network subnet name.
     */
    name: string;
    /**
     * The network subnet description.
     */
    description?: string;
    /**
     * The network subnet CIDR (e.g. 192.168.0.0/24).
     */
    cidr: string;
    /**
     * The network subnet router/gateway IP address (e.g. 192.168.0.254).
     */
    gateway: string;
    /**
     * The network subnet DNS server IP address (gateway value if unspecified).
     */
    dns?: string;
    /**
     * The list of extra routes to be access through designated gateway (format is 10.0.0.0/8).
     */
    extra_routes?: Array<string>;
    /**
     * The network subnet reserved IPv4 ranges (i.e. no IP address can be assigned from there).
     */
    reserved?: Array<IpRange>;
    /**
     * The network subnet IPv4 ranges reserved for per-zone local network gateways (range size must be at least equal to region number of zones).
     */
    gw_pool?: Array<IpRange>;
    /**
     * Optional application service type.
     */
    application?: Subnet.ApplicationEnum;
}
export namespace Subnet {
    export type ApplicationEnum = 'ceph' | 'user';
    export const ApplicationEnum = {
        Ceph: 'ceph' as ApplicationEnum,
        User: 'user' as ApplicationEnum
    };
}


