/**
 * Kowabunga API documentation
 *
 * Contact: maintainers@kowabunga.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A image template.
 */
export interface Template { 
    /**
     * The image template ID (auto-generated).
     */
    id?: string;
    /**
     * The image template name.
     */
    name: string;
    /**
     * The image template description.
     */
    description?: string;
    /**
     * Type of operating system if OS kind (useful to determine cloud-init parameters for instance).
     */
    os?: Template.OsEnum;
    /**
     * HTTP(s) source URL of the KVM-ready OS image.
     */
    source: string;
}
export namespace Template {
    export type OsEnum = 'linux' | 'windows';
    export const OsEnum = {
        Linux: 'linux' as OsEnum,
        Windows: 'windows' as OsEnum
    };
}


