/**
 * Kowabunga API documentation
 *
 * Contact: maintainers@kowabunga.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A Kowabunga user login credentials.
 */
export interface UserCredentials { 
    /**
     * The user email address for login.
     */
    email: string;
    /**
     * The user password for login.
     */
    password: string;
    /**
     * The resulting server-generated JWT token for Bearer Authentication (read-only).
     */
    jwt?: string;
}

