/**
 * Kowabunga API documentation
 *
 * Contact: maintainers@kowabunga.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A storage volume.
 */
export interface Volume { 
    /**
     * The storage volume ID (auto-generated).
     */
    id?: string;
    /**
     * The storage volume name.
     */
    name: string;
    /**
     * The storage volume description.
     */
    description?: string;
    /**
     * The storage volume type.
     */
    type: Volume.TypeEnum;
    /**
     * The storage volume size (in bytes).
     */
    size: number;
}
export namespace Volume {
    export type TypeEnum = 'os' | 'iso' | 'raw';
    export const TypeEnum = {
        Os: 'os' as TypeEnum,
        Iso: 'iso' as TypeEnum,
        Raw: 'raw' as TypeEnum
    };
}


