/**
 * Kowabunga API documentation
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * The version of the OpenAPI document: 0.52.5
 * Contact: maintainers@kowabunga.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* A Kowabunga authentication security token consists of an API key granting access to resources.
*/
export class ApiToken {
    /**
    * The server-to-server authentication security token ID (auto-generated).
    */
    'id'?: string;
    /**
    * The server-to-server authentication security token name.
    */
    'name': string;
    /**
    * The server-to-server authentication security token description.
    */
    'description'?: string;
    /**
    * Does the API token expires at some stage ?.
    */
    'expire': boolean = false;
    /**
    * Expiration date of the token (YYYY-MM-DD format).
    */
    'expirationDate'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "expire",
            "baseName": "expire",
            "type": "boolean"
        },
        {
            "name": "expirationDate",
            "baseName": "expiration_date",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ApiToken.attributeTypeMap;
    }
}

