/**
 * Kowabunga API documentation
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * The version of the OpenAPI document: 0.52.5
 * Contact: maintainers@kowabunga.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* A virtual machine instance.
*/
export class Instance {
    /**
    * The virtual machine instance ID (auto-generated).
    */
    'id'?: string;
    /**
    * The virtual machine instance name.
    */
    'name': string;
    /**
    * The virtual machine instance description.
    */
    'description'?: string;
    /**
    * The virtual machine instance memory size (in bytes).
    */
    'memory': number;
    /**
    * The virtual machine instance number of vCPUs.
    */
    'vcpus': number;
    /**
    * a list of existing network adapters to be connected to the instance.
    */
    'adapters'?: Array<string>;
    /**
    * volumes list of existing storage volumes (i.e. disks) to be connected to the instance.
    */
    'volumes'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "memory",
            "baseName": "memory",
            "type": "number"
        },
        {
            "name": "vcpus",
            "baseName": "vcpus",
            "type": "number"
        },
        {
            "name": "adapters",
            "baseName": "adapters",
            "type": "Array<string>"
        },
        {
            "name": "volumes",
            "baseName": "volumes",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return Instance.attributeTypeMap;
    }
}

