/**
 * Kowabunga API documentation
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * The version of the OpenAPI document: 0.52.5
 * Contact: maintainers@kowabunga.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Cost } from './cost';

/**
* A Kaktus (Kowabunga Affordable KVM and Tight Underneath Storage) is an hyper-converged infrastructure (HCI) bare-metal node offering computing and distributed storage capabilites.
*/
export class Kaktus {
    /**
    * The Kaktus computing node ID (auto-generated).
    */
    'id'?: string;
    /**
    * The Kaktus computing node name.
    */
    'name': string;
    /**
    * The Kaktus computing node description.
    */
    'description'?: string;
    'cpuCost'?: Cost;
    'memoryCost'?: Cost;
    /**
    * The Kaktus node CPU resource over-commit ratio. Overcommitting CPU resources for VMs means allocating more virtual CPUs (vCPUs) to the virtual machines (VMs) than the physical cores available on the node. This can help optimize the utilization of the node CPU and increase the density of VMs per node.
    */
    'overcommitCpuRatio'?: number = 3;
    /**
    * The Kaktus node memory resource over-commit ratio. Memory overcommitment is a concept in computing that covers the assignment of more memory to virtual computing devices (or processes) than the physical machine they are hosted, or running on, actually has.
    */
    'overcommitMemoryRatio'?: number = 2;
    /**
    * a list of existing remote agents managing the Kaktus node.
    */
    'agents': Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "cpuCost",
            "baseName": "cpu_cost",
            "type": "Cost"
        },
        {
            "name": "memoryCost",
            "baseName": "memory_cost",
            "type": "Cost"
        },
        {
            "name": "overcommitCpuRatio",
            "baseName": "overcommit_cpu_ratio",
            "type": "number"
        },
        {
            "name": "overcommitMemoryRatio",
            "baseName": "overcommit_memory_ratio",
            "type": "number"
        },
        {
            "name": "agents",
            "baseName": "agents",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return Kaktus.attributeTypeMap;
    }
}

