/**
 * Kowabunga API documentation
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * The version of the OpenAPI document: 0.52.5
 * Contact: maintainers@kowabunga.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { KawaiiNetIpZone } from './kawaiiNetIpZone';

/**
* A Kawaii Network IP settings.
*/
export class KawaiiNetIp {
    /**
    * The Kawaii global public gateways virtual IP addresses (read-only).
    */
    '_public': Array<string>;
    /**
    * The Kawaii global private gateways virtual IP addresses (read-only).
    */
    '_private': Array<string>;
    /**
    * The Kawaii per-zone list of Kowabunga virtual IP addresses.
    */
    'zones': Array<KawaiiNetIpZone>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "_public",
            "baseName": "public",
            "type": "Array<string>"
        },
        {
            "name": "_private",
            "baseName": "private",
            "type": "Array<string>"
        },
        {
            "name": "zones",
            "baseName": "zones",
            "type": "Array<KawaiiNetIpZone>"
        }    ];

    static getAttributeTypeMap() {
        return KawaiiNetIp.attributeTypeMap;
    }
}

