/**
 * Kowabunga API documentation
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * The version of the OpenAPI document: 0.52.5
 * Contact: maintainers@kowabunga.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* A Kowabunga user.
*/
export class User {
    /**
    * The Kowabunga user ID (auto-generated).
    */
    'id'?: string;
    /**
    * The Kowabunga user name.
    */
    'name': string;
    /**
    * The Kowabunga user description.
    */
    'description'?: string;
    /**
    * User email address.
    */
    'email': string;
    /**
    * The Kowabunga user role.
    */
    'role': User.RoleEnum;
    /**
    * Whether or not to receive email notifications on events.
    */
    'notifications'?: boolean = false;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "role",
            "baseName": "role",
            "type": "User.RoleEnum"
        },
        {
            "name": "notifications",
            "baseName": "notifications",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return User.attributeTypeMap;
    }
}

export namespace User {
    export enum RoleEnum {
        SuperAdmin = <any> 'superAdmin',
        ProjectAdmin = <any> 'projectAdmin',
        User = <any> 'user'
    }
}
