export * from './adapter.service';
import { AdapterService } from './adapter.service';
export * from './agent.service';
import { AgentService } from './agent.service';
export * from './instance.service';
import { InstanceService } from './instance.service';
export * from './kaktus.service';
import { KaktusService } from './kaktus.service';
export * from './kawaii.service';
import { KawaiiService } from './kawaii.service';
export * from './kiwi.service';
import { KiwiService } from './kiwi.service';
export * from './kompute.service';
import { KomputeService } from './kompute.service';
export * from './konvey.service';
import { KonveyService } from './konvey.service';
export * from './kylo.service';
import { KyloService } from './kylo.service';
export * from './nfs.service';
import { NfsService } from './nfs.service';
export * from './pool.service';
import { PoolService } from './pool.service';
export * from './project.service';
import { ProjectService } from './project.service';
export * from './record.service';
import { RecordService } from './record.service';
export * from './region.service';
import { RegionService } from './region.service';
export * from './subnet.service';
import { SubnetService } from './subnet.service';
export * from './team.service';
import { TeamService } from './team.service';
export * from './template.service';
import { TemplateService } from './template.service';
export * from './token.service';
import { TokenService } from './token.service';
export * from './user.service';
import { UserService } from './user.service';
export * from './vnet.service';
import { VnetService } from './vnet.service';
export * from './volume.service';
import { VolumeService } from './volume.service';
export * from './zone.service';
import { ZoneService } from './zone.service';
export const APIS = [AdapterService, AgentService, InstanceService, KaktusService, KawaiiService, KiwiService, KomputeService, KonveyService, KyloService, NfsService, PoolService, ProjectService, RecordService, RegionService, SubnetService, TeamService, TemplateService, TokenService, UserService, VnetService, VolumeService, ZoneService];
